In [14]:
import pandas as pd
import numpy as np
from keras.layers import Dense, LSTM, SimpleRNN, Embedding
from keras.models import Sequential
from keras.utils.np_utils import to_categorical
import os
os.chdir("C:\\Users\\pc\\Desktop\\DataScience Batch 41\\cute 5\\20180707_Batch41_CSE 7321c_CUTe_PartC")

In [16]:
raw_data = pd.read_csv('AuthorsDataset.csv', encoding='latin-1')


print(raw_data.shape)
print(raw_data.columns)
print(raw_data)

(750, 2)
Index(['Text', 'Author'], dtype='object')
                                                  Text     Author
0    I give Pirrip as my father's family name, on t...    Charles
1    Ours was the marsh country, down by the river,...    Charles
2    You bring me, to-morrow morning early, that fi...    Charles
3    The marshes were just a long black horizontal ...    Charles
4    My sister, Mrs. Joe, with black hair and eyes,...    Charles
5    My sister had a trenchant way of cutting our b...    Charles
6    The effort of resolution necessary to the achi...    Charles
7    Some medical beast had revived Tar-water in th...    Charles
8    Conscience is a dreadful thing when it accuses...    Charles
9    As soon as the great black velvet pall outside...    Charles
10   The mist was heavier yet when I got out upon t...    Charles
11   All this time, I was getting on towards the ri...    Charles
12   Why, see now! said he. When a man's alone on t...    Charles
13   I indicated in what 

In [17]:
from sklearn.utils import shuffle

data= shuffle(raw_data)

print(data)

                                                  Text     Author
322  From the conception of mechanical force as com...    HGWells
331  There is nothing in machinery, there is nothin...    HGWells
741  By that time we had the fire lighted, and a bo...  Stevenson
545  It was a blessed thing indeed to open my eyes ...  Stevenson
47   Saving for the one weird smile at first, I sho...    Charles
310  In Utopia there is no distinct and separate sc...    HGWells
421  But these, of course, are generalisations. The...    HGWells
96   As I never assisted at any other representatio...    Charles
102  Now, as to Orlick; he had gone to town exactly...    Charles
546  Here I lay for the space of many days a close ...  Stevenson
679  This was but one of Cluny's hiding-places; he ...  Stevenson
578  Ah! says he, falling again to smiling, I got m...  Stevenson
683  I do not know if the collops were truly very g...  Stevenson
126  I selected the materials for a suit, with the ...    Charles
265  The l

In [18]:
from sklearn.model_selection import train_test_split

In [21]:
train,test = train_test_split(data, test_size = 0.2) 
print(train.shape)
print(test.shape)

(600, 2)
(150, 2)


In [22]:
train.columns

Index(['Text', 'Author'], dtype='object')

In [26]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(train.Text)

train_x = tokenizer.texts_to_sequences(train.Text)
train_x = pad_sequences(train_x, maxlen=100)
test_x = tokenizer.texts_to_sequences(test.Text)
test_x = pad_sequences(test_x, maxlen=100)

train_x.shape, test_x.shape

((600, 100), (150, 100))

In [27]:
print(train_x)

[[  28 2847 1880 ...   38  836 1233]
 [  13   17  777 ...    5  310   41]
 [   1  839    1 ...  686    2  379]
 ...
 [  24    6  926 ...   35  677   37]
 [   8 1362    7 ...   22    8 2198]
 [ 551  104    8 ...   68   25 1553]]


In [38]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index), input_length=100, output_dim=100))
model.add(LSTM(10, return_sequences=False))
model.add(Dense(3, activation='softmax'))

In [39]:
unique_labels = list(data.Author.unique())
train_y = np.array([unique_labels.index(i) for i in train.Author])
train_y = to_categorical(train_y)
test_y_ = np.array([unique_labels.index(i) for i in test.Author])
test_y = to_categorical(test_y_)


In [40]:
print(train_y.shape)
print(test_y.shape)
print(train_x.shape)
print(test_x.shape)

(600, 3)
(150, 3)
(600, 100)
(150, 100)


In [42]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_x, train_y, epochs=20, validation_split=0.25)

Train on 450 samples, validate on 150 samples
Epoch 1/20
450/450 [==============================] - 3s 6ms/step - loss: 1.0150 - acc: 0.8733 - val_loss: 1.0479 - val_acc: 0.6067
Epoch 2/20
450/450 [==============================] - 1s 2ms/step - loss: 0.9303 - acc: 0.9356 - val_loss: 1.0049 - val_acc: 0.6333
Epoch 3/20
450/450 [==============================] - 1s 3ms/step - loss: 0.7985 - acc: 0.9289 - val_loss: 0.9261 - val_acc: 0.6400
Epoch 4/20
450/450 [==============================] - 1s 2ms/step - loss: 0.6202 - acc: 0.9267 - val_loss: 0.8192 - val_acc: 0.7200
Epoch 5/20
450/450 [==============================] - 1s 2ms/step - loss: 0.4311 - acc: 0.9822 - val_loss: 0.6800 - val_acc: 0.7733
Epoch 6/20
450/450 [==============================] - 1s 2ms/step - loss: 0.2738 - acc: 0.9978 - val_loss: 0.5524 - val_acc: 0.8200
Epoch 7/20
450/450 [==============================] - 1s 2ms/step - loss: 0.1699 - acc: 0.9978 - val_loss: 0.5465 - val_acc: 0.8000
Epoch 8/20
450/450 [==========

In [44]:
y_pred= model.predict_classes(test_x)
print()


In [45]:
from sklearn import metrics
#metrics.accuracy_score(y_true=raw_test_data.Label,y_pred=y_pred)
metrics.accuracy_score(y_true=test_y_ ,y_pred=y_pred)

0.8066666666666666